//import FooterMobile from '@/components/FooterMobile/page'
import styles from "./page.module.css";

//import HeaderTop from '@/components/HeaderTop/page'
//import MessageClear from "@/components/MessageClear/page";
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function BasketLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div id='detail' className={styles.item}>
            {children}
        </div>
    )
}
