import SVG from "@/components/SVG/page";
import MessageClear from "@/components/MessageClear/page";

import styles from "./page.module.css";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function BasketLayout({
    children,
}: {
    children: React.ReactNode
}) {
    //<div id="emptyCount"></div>

    return (
        <div className={styles.wrap}>
            <div className={styles.wrapRow}>
                <SVG />
                <div className={styles.wrapColumn}>
                    <MessageClear />
                    {children}
                </div>
            </div>
            <footer className={styles.footer}>
                © Все права и планета защищены
            </footer>
        </div>

    )
}
