import SVG from "@/components/SVG/page";
import MessageClear from "@/components/MessageClear/page";

import styles from "./page.module.css";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function BasketLayout({
    children,
}: {
    children: React.ReactNode
}) {
    //<div id="emptyCount"></div>
    //<div className={styles.wrapRow}>

    return (
        <div className={styles.wrapLayout}>
            <SVG />
            <div className={styles.wrapRowRight}>
                <div className={styles.wrapRow}>
                    <MessageClear />
                    <div className={styles.wrap}>
                        {children}
                    </div>
                </div>
                <footer className={styles.footer}>
                    © Все права и планета защищены
                </footer>
            </div>
        </div>

    )
}
