import { Suspense, createElement } from 'react'
import HeaderTop from '@/components/HeaderTop/page';
import dynamic from 'next/dynamic'
//import IOComponent from '@/components/IOComponent/page';

const IOComponent = dynamic(() => import('../components/IOComponent/page'), {
  loading: () => <span>Loading...</span>, ssr: false
})
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout(props: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body>
        <div id='__next'>
          <HeaderTop />
          <Suspense fallback={<span> loading root...</span>}>
            {props.children}
          </Suspense >
          <div id='forScroll'></div>
          <IOComponent />
        </div>
      </body>
    </html >
  )
}
