import { Suspense, createElement } from 'react'
import IOComponent from '@/components/IOComponent/page';

import HeaderTop from '@/components/HeaderTop/page';
//import Script from 'next/script'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout(props: {
  children: React.ReactNode,
}) {
  //  <!DOCTYPE html >
  return (
    <html lang="en">
      <body>
        <div id='__next'>
          <HeaderTop />
          <Suspense fallback={<span> loading root...</span>}>
            {props.children}
          </Suspense >
          <div id='forScroll'></div>
          <IOComponent />
        </div>
      </body>
    </html >
  )
}
